# Generated by Django 4.1.3 on 2022-11-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter car reg. number', max_length=10, verbose_name='number')),
                ('vin', models.CharField(help_text='Enter VIN', max_length=17, verbose_name='VIN')),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Enter car make', max_length=100, verbose_name='Make')),
                ('model', models.CharField(help_text='Enter car model', max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='year')),
                ('engine', models.CharField(max_length=20, verbose_name='Engine')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First name')),
                ('surname', models.CharField(max_length=100, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Order date')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.car')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter service name', max_length=100, verbose_name='Service name')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.IntegerField(verbose_name='PCS.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.car_model'),
        ),
    ]
