# Generated by Django 4.1.3 on 2022-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_price_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='car',
        ),
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ManyToManyField(to='autoservice.car_model'),
        ),
    ]
