# Generated by Django 4.1.3 on 2022-11-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_remove_price_car_service_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_id',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autoservice.price'),
        ),
    ]
