# Generated by Django 4.1.3 on 2022-11-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_remove_order_client_id_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
    ]
